# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 605a67cf7af39903e1072feb64a3b0a72a14b3c1f85fd29cd4617b632b11d2f8d767ea92197a1d713ea446a55135e9c2b7ee0c2215f6ed036ee08007fe42ab9e

test:
  secret_key_base: 1b3bc8d13949f9e20bad88c7c7dec1d29078b94538e196b7b14f5def4c9cf9901ebd0c5a9ece87201957b9ef944c5ee1977cb0241cd0af617164cca026a053ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
